### ISSUE TITLE
打卡失败，有些问题想要一起讨论下

### ISSUE THREAD

**Issue by Dispa1r** [zombie12138/inuaa#1]
emm不知道为啥抓包总是失败，甚至正常情况下都无法打开登录界面，逆了下这个app，找到一些接口，但是不知道哪些是有用的，打算hook验证看看，希望能一起讨论下

**Comment by zombie12138** [comment]
> emm不知道为啥抓包总是失败，甚至正常情况下都无法打开登录界面，逆了下这个app，找到一些接口，但是不知道哪些是有用的，打算hook验证看看，希望能一起讨论下

我是直接网页抓的包😓

**Comment by Dispa1r** [comment]
才发现有网页版2333
